# golangci-lint configuration for OSS repos
# Based on Kubernetes and OSS best practices
# Compatible with golangci-lint v2.7.2 (no version field, like zen-lead/zen-gc/zen-lock)

run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gocyclo
    - gosec
    - goimports
