# golangci-lint configuration for OSS repos
# Based on Kubernetes and OSS best practices
# Migrated to v2 format per https://golangci-lint.run/docs/product/migration-guide

version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck  # Includes gosimple (merged in v2)
    - unused
    - ineffassign
    - misspell
    - gocyclo
    - gosec

formatters:
  enable:
    - gofmt
    - goimports
