# golangci-lint configuration for OSS repos
# Based on Kubernetes and OSS best practices

run:
  timeout: 5m
  tests: true
  go: "1.24"

linters:
  enable:
    # Essential linters
    - gofmt          # Checks whether code was gofmt-ed
    - govet          # Vet examines Go source code and reports suspicious constructs
    - errcheck       # Checks for unchecked errors
    - staticcheck    # Staticcheck is a go vet on steroids
    - unused         # Checks for unused constants, variables, functions and types
    - gosimple       # Linter for Go source code that specializes in simplifying code
    - ineffassign    # Detects when assignments to existing variables are not used
    - misspell       # Finds commonly misspelled English words in comments
    - gocyclo        # Computes and checks the cyclomatic complexity of functions
    - gosec          # Inspects source code for security problems
    - goimports      # Goimports does everything that gofmt does plus imports sorting

linters-settings:
  gofmt:
    simplify: true
  
  gocyclo:
    min-complexity: 15
  
  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G204  # Subprocess launched with variable (acceptable for kubectl)

issues:
  exclude-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - tmp
    - bin
    - deploy
    - charts
    - .github
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
    - "zz_generated\\.deepcopy\\.go$"
  exclude-rules:
    # Exclude test files from some checks
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
    
    # Exclude generated files
    - path: zz_generated\.deepcopy\.go
      linters:
        - all

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

