# golangci-lint configuration for OSS repos
# Based on Kubernetes and OSS best practices
# Compatible with golangci-lint v2.7.2 (same format as zen-flow)

version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  enable:
    # Linters only (formatters like gofmt/goimports not allowed with version: "2")
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gocyclo
    - gosec
