apiVersion: zen.kube-zen.io/v1alpha1
kind: Ingester
metadata:
  name: trivy-dynamic-webhook
  namespace: zen-system
spec:
  source: trivy
  ingester: webhook
  
  webhook:
    path: "/ingest/trivy"
    methods: ["POST"]
    bufferSize: 200
    auth:
      type: bearer
      secretName: trivy-webhook-token
    rateLimit:
      requestsPerSecond: 100
      burst: 200
  
  destinations:
    - type: crd
      value: observations
      mapping:
        domain: security
        type: vulnerability_scan
        priority:
          CRITICAL: 0.9
          HIGH: 0.7
          MEDIUM: 0.5
          LOW: 0.3
        fieldMapping:
          - from: "$.Target"
            to: "target_resource"
            transform: "lower"
          - from: "$.VulnID"
            to: "vulnerability_id"
          - from: "$.Severity"
            to: "severity_level"
          - from: "$.Description"
            to: "description"
            transform: "truncate:200"
  
  filters:
    enabled: true
    minPriority: 0.3
  deduplication:
    enabled: true
    window: "1h"
    strategy: fingerprint
  optimization:
    enabled: true
    order: auto
    autoOptimize: true

