apiVersion: zen.kube-zen.io/v1
kind: Ingester
metadata:
  name: trivy-informer
  namespace: default
spec:
  source: trivy
  ingester: informer
  informer:
    gvr:
      group: aquasecurity.github.io
      version: v1alpha1
      resource: vulnerabilityreports
    resyncPeriod: "30m"
  filters:
    enabled: true
    minPriority: 0.3
    excludeNamespaces:
      - kube-system
      - kube-public
  deduplication:
    enabled: true
    window: "1h"
    strategy: fingerprint
  optimization:
    enabled: true
    order: auto
    autoOptimize: true
    analysisInterval: "15m"
    confidenceThreshold: 0.7
  destinations:
    - type: crd
      value: observations
      mapping:
        domain: security
        type: vulnerability
        priority:
          CRITICAL: 0.9
          HIGH: 0.7
          MEDIUM: 0.5
          LOW: 0.3
        fieldMapping:
          - from: vulnerabilityID
            to: cve_id
          - from: resource.kind
            to: resource_kind
          - from: resource.name
            to: resource_name

