apiVersion: zen.kube-zen.io/v1alpha1
kind: Ingester
metadata:
  name: trivy-informer
  namespace: default
spec:
  source: trivy
  ingester: informer
  informer:
    gvr:
      group: aquasecurity.github.io
      version: v1alpha1
      resource: vulnerabilityreports
    resyncPeriod: "30m"
  destinations:
    - type: crd
      value: observations

