# Security Event: Vulnerability Detection (Trivy-style)
# Represents a CVE detected in a container image
apiVersion: zen.kube-zen.io/v1
kind: Observation
metadata:
  generateName: trivy-vuln-
  namespace: default
  labels:
    zen.io/source: "trivy"
    zen.io/type: "vulnerability"
    zen.io/priority: "high"
spec:
  source: "trivy"
  category: "security"
  severity: "high"
  eventType: "vulnerability"
  resource:
    apiVersion: "v1"
    kind: "Pod"
    name: "my-app-abc123"
    namespace: "production"
  details:
    cve: "CVE-2024-1234"
    package: "openssl"
    installedVersion: "1.1.1"
    fixedVersion: "1.1.2"
    cvssScore: 7.5
    severity: "HIGH"
    description: "OpenSSL vulnerability allows remote code execution"
  detectedAt: "2025-12-10T12:00:00Z"
  ttlSecondsAfterCreation: 2592000  # 30 days
