apiVersion: zen.kube-zen.io/v1alpha1
kind: Ingester
metadata:
  name: high-rate-ingester
  namespace: zen-system
spec:
  source: kubernetes-events
  ingester: informer
  informer:
    gvr:
      group: ""
      version: "v1"
      resource: "events"
    namespace: ""
    resyncPeriod: "0"
  
  rateLimit:
    enabled: true
    requestsPerSecond: 2000
    burst: 4000
  
  # Processing pipeline configuration (canonical format)
  # Canonical pipeline: source → (filter | dedup) → normalize → destinations[]
  # See zen-watcher/docs/INGESTER_API.md for complete API documentation
  processing:
    filter:
      enabled: true
      minPriority: 0.3
      excludeNamespaces:
        - kube-system
        - kube-public
    dedup:
      enabled: true
      window: "5m"
      strategy: event-stream  # event-stream for high-volume, noisy sources
      maxEventsPerWindow: 1000  # Optional: strict limit for event-stream
    optimization:
      enabled: true
      order: auto
      analysisInterval: "15m"
      confidenceThreshold: 0.7
      thresholds:
        dedupEffectiveness:
          warning: 0.5
          critical: 0.3
        lowSeverityPercent:
          warning: 0.7
          critical: 0.9
        observationsPerMinute:
          warning: 100
          critical: 500
  
  # Backward compatibility fields (maps to processing.*)
  # but new examples should use spec.processing.* as the primary form
  filters:
    enabled: true
    minPriority: 0.3
    excludeNamespaces:
      - kube-system
      - kube-public
  deduplication:
    enabled: true
    window: "5m"
    strategy: fingerprint
  
  
  # Destinations: where events go
  destinations:
    # Classic zen-watcher OSS behavior: write Observation CRDs
    - type: crd
      value: observations
      mapping:
        domain: operations
        type: kubernetes_event
        priority:
          Warning: 0.7
          Normal: 0.3
          Error: 0.9
    
    # Optional: send to external webhook with retry policy
    - type: webhook
      name: eu-mirror
      url: "https://eu-hooks.example.com/t/k8s-events"
      retryPolicy:
        maxRetries: 10
        backoff: exponential
        timeout: "30s"
