# Complete Ingester Example - Demonstrating All Ingester Types
# This example shows how to configure different ingester types in Zen Watcher
#
# For multi-destination examples, see: multi-destination-ingester.yaml

---
# Example 1: Informer Ingester (for CRD-based tools like Trivy, Kyverno)
apiVersion: zen.kube-zen.io/v1alpha1
kind: Ingester
metadata:
  name: trivy-informer-example
  namespace: zen-system
spec:
  source: trivy
  ingester: informer
  informer:
    gvr:
      group: aquasecurity.github.io
      version: v1alpha1
      resource: vulnerabilityreports
    namespace: ""  # Empty = all namespaces
    resyncPeriod: "30m"
  normalization:
    domain: security
    type: vulnerability
    priority:
      CRITICAL: 0.9
      HIGH: 0.7
      MEDIUM: 0.5
      LOW: 0.3
  filter:
    minPriority: 0.3
  # Deduplication (v1.1+ canonical location)
  processing:
    dedup:
      window: "1h"
      strategy: fingerprint  # Default - can be omitted
    # Note: order/optimization is commercial-only (not in OSS base)
  # Legacy dedup (backward compatibility)
  dedup:
    window: "1h"
    strategy: fingerprint
  destinations:
    - type: crd
      value: observations

---
# Example 2: Webhook Ingester (for push-based tools like Falco, Audit)
apiVersion: zen.kube-zen.io/v1alpha1
kind: Ingester
metadata:
  name: falco-webhook-example
  namespace: zen-system
spec:
  source: falco
  ingester: webhook
  webhook:
    path: "/webhooks/falco"
    port: 8080
    bufferSize: 1000
    auth:
      type: bearer
      secretName: falco-webhook-token
  normalization:
    domain: security
    type: runtime_threat
  filter:
    minPriority: 0.5
  dedup:
    window: "5m"
    strategy: fingerprint
  destinations:
    - type: crd
      value: observations

---
# Example 3: Logs Ingester (for log-based monitoring)
apiVersion: zen.kube-zen.io/v1alpha1
kind: Ingester
metadata:
  name: sealed-secrets-logs-example
  namespace: zen-system
spec:
  source: sealed-secrets
  ingester: logs
  logs:
    podSelector: app=sealed-secrets
    container: sealed-secrets
    patterns:
      - regex: "ERROR.*(?P<message>.*)"
        type: error
        priority: 0.7
      - regex: "WARN.*(?P<message>.*)"
        type: warning
        priority: 0.5
    sinceSeconds: 300
    pollInterval: "10s"
  normalization:
    domain: operations
    type: log_error
  filter:
    minPriority: 0.4
  destinations:
    - type: crd
      value: observations

---
# Example 4: ConfigMap Ingester (for batch tools like Checkov, Kube-Bench)
# Uses informer with GVR to watch ConfigMaps
apiVersion: zen.kube-zen.io/v1alpha1
kind: Ingester
metadata:
  name: checkov-cm-example
  namespace: zen-system
spec:
  source: checkov
  ingester: informer
  informer:
    gvr:
      group: ""
      version: "v1"
      resource: "configmaps"
    namespace: ""
    labelSelector: app=checkov
    resyncPeriod: "30m"
  normalization:
    domain: security
    type: iac_vulnerability
    priority:
      CRITICAL: 0.9
      HIGH: 0.7
      MEDIUM: 0.5
      LOW: 0.3
  filter:
    minPriority: 0.3
  dedup:
    window: "2h"
    strategy: fingerprint
  destinations:
    - type: crd
      gvr:
        group: ""
        version: "v1"
        resource: "configmaps"
      mapping:
        domain: security
        type: iac_vulnerability

---
# Example 5: Kubernetes Events Ingester (using informer)
apiVersion: zen.kube-zen.io/v1alpha1
kind: Ingester
metadata:
  name: kubernetes-events-example
  namespace: zen-system
spec:
  source: kubernetes-events
  ingester: informer
  informer:
    gvr:
      group: ""
      version: "v1"
      resource: "events"
    namespace: ""
    resyncPeriod: "0"
  normalization:
    domain: operations
    type: kubernetes_event
  filter:
    minPriority: 0.2
    excludeNamespaces:
      - kube-system
      - kube-public
  # Deduplication (v1.1+ canonical location)
  processing:
    dedup:
      window: "10m"
      strategy: event-stream  # event-stream for noisy k8s events
    # Note: order/optimization is commercial-only (not in OSS base)
  # Legacy dedup (backward compatibility)
  dedup:
    window: "10m"
    strategy: fingerprint
  destinations:
    - type: crd
      value: observations

