apiVersion: zen.kube-zen.io/v1alpha1
kind: Ingester
metadata:
  name: pure-webhook-ingester
  namespace: zen-system
spec:
  source: github-webhooks
  ingester: webhook
  
  webhook:
    path: "/ingest/github"
    methods: ["POST"]
    auth:
      type: hmac
      secretRef: github-webhook-secret
    tls:
      enabled: true
      certSecretRef: github-tls-cert
      minVersion: "1.3"
    rateLimit:
      requestsPerSecond: 100
      burst: 200
    bufferSize: 1000
  
  # Normalization via destination mapping
  destinations:
    - type: webhook
      name: primary-sink
      url: "https://api.example.com/webhooks/github"
      mapping:
        domain: operations
        type: github_event
        priority:
          push: 0.5
          pull_request: 0.7
          issue: 0.6
          release: 0.8
        fieldMapping:
          - from: "$.repository.full_name"
            to: "repository"
          - from: "$.action"
            to: "action"
          - from: "$.sender.login"
            to: "actor"
      retryPolicy:
        maxRetries: 5
        backoff: exponential
        timeout: "10s"
    
    - type: webhook
      name: backup-sink
      url: "https://backup.example.com/events/github"
      retryPolicy:
        maxRetries: 3
        backoff: linear
        timeout: "5s"
  
  # Filtering
  filters:
    enabled: true
    minPriority: 0.4
  
  # Deduplication (v1.1+ canonical location)
  processing:
    dedup:
      enabled: true
      window: "1h"
      strategy: fingerprint  # Default strategy (can be omitted)
    order: filter_first
    autoOptimize: false
  
  # Legacy deduplication (backward compatibility - maps to processing.dedup)
  deduplication:
    enabled: true
    window: "1h"
    strategy: fingerprint
  
  # Optimization
  optimization:
    enabled: true
    order: filter_first
    autoOptimize: false
