apiVersion: zen.kube-zen.io/v1alpha1
kind: Ingester
metadata:
  name: sealed-secrets-config
spec:
  source: sealed-secrets
  ingester: logs
  logs:
    podSelector: app=sealed-secrets-controller
    container: ""
    patterns:
      - regex: 'decryption failed.*namespace="(?P<namespace>[^"]+)".*name="(?P<name>[^"]+)"'
        type: decryption_failure
        priority: 0.8
      - regex: 'unable to decrypt.*secret.*(?P<reason>[^\n]+)'
        type: decryption_error
        priority: 0.9
      - regex: 'error.*sealed.*secret.*(?P<message>[^\n]+)'
        type: sealed_secret_error
        priority: 0.7
    sinceSeconds: 300
    pollInterval: "1s"
  normalization:
    domain: security
    type: secret_decryption_failure
    fieldMapping:
      - from: matches.namespace
        to: namespace
      - from: matches.name
        to: secret_name
      - from: matches.reason
        to: reason
  filter:
    minPriority: 0.6
  dedup:
    window: "10m"
    strategy: fingerprint
  thresholds:
    observationsPerMinute:
      warning: 5
      critical: 15
    custom:
      - name: rapid_failures
        field: raw.matches
        operator: contains
        value: "decryption failed"
        message: "High frequency of decryption failures - potential credential attack"
  rateLimit:
    observationsPerMinute: 20
    burst: 3
  destinations:
    - type: crd
      value: observations

