# Example: Trivy cluster vulnerability scanner
# Uses informer to watch Trivy scan results stored in ConfigMaps
apiVersion: zen.kube-zen.io/v1
kind: Ingester
metadata:
  name: trivy-cluster-vuln
  namespace: default
spec:
  source: trivy-cluster
  ingester: informer
  informer:
    gvr:
      group: ""
      version: "v1"
      resource: "configmaps"
    namespace: ""
    labelSelector: "app=trivy,type=cluster-scan"
    resyncPeriod: "30m"
  normalization:
    domain: security
    type: vulnerability
    priority:
      CRITICAL: 0.9
      HIGH: 0.7
      MEDIUM: 0.5
      LOW: 0.3
    fieldMapping:
      - from: "$.vulnerability.id"
        to: "vuln-id"
      - from: "$.vulnerability.severity"
        to: "severity"
      - from: "$.vulnerability.package"
        to: "package"
  filter:
    minPriority: 0.3
    excludeNamespaces:
      - "kube-system"
  dedup:
    enabled: true
    window: "2h"
    strategy: fingerprint
    fields:
      - "spec.source"
      - "vuln-id"
  processing:
    order: filter_first
