apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: observationmappings.zen.kube-zen.io
spec:
  group: zen.kube-zen.io
  names:
    kind: ObservationMapping
    listKind: ObservationMappingList
    plural: observationmappings
    singular: observationmapping
    shortNames:
      - obsmapping
      - omapping
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["sourceName", "group", "version", "kind"]
              properties:
                sourceName:
                  type: string
                  description: "Source name for Observations created from this mapping (e.g., trivy, mytool)"
                  pattern: "^[a-z0-9-]+$"
                group:
                  type: string
                  description: "API group of the source CRD (e.g., aquasecurity.github.io)"
                version:
                  type: string
                  description: "API version of the source CRD (e.g., v1alpha1)"
                kind:
                  type: string
                  description: "Kind of the source CRD (e.g., VulnerabilityReport)"
                # Field mappings - JSONPath expressions or static values
                mappings:
                  type: object
                  description: "Field mappings from source CRD to Observation Event"
                  properties:
                    severity:
                      type: string
                      description: "JSONPath to severity field, or static value. Examples: '.report.summary.criticalCount', 'HIGH'"
                    category:
                      type: string
                      description: "JSONPath to category field, or static value. Default: 'security'"
                    eventType:
                      type: string
                      description: "JSONPath to eventType field, or static value. Default: 'custom-event'"
                    message:
                      type: string
                      description: "JSONPath to message/description field (optional)"
                    resource:
                      type: object
                      description: "Resource reference mappings"
                      properties:
                        apiVersion:
                          type: string
                          description: "JSONPath to resource apiVersion (e.g., '.report.resource.apiVersion')"
                        kind:
                          type: string
                          description: "JSONPath to resource kind (e.g., '.report.resource.kind')"
                        name:
                          type: string
                          description: "JSONPath to resource name (e.g., '.report.resource.name')"
                        namespace:
                          type: string
                          description: "JSONPath to resource namespace (e.g., '.report.resource.namespace' or '.metadata.namespace')"
                    details:
                      type: object
                      description: "JSONPath expressions for additional details (optional). All matched fields go into spec.details"
                      x-kubernetes-preserve-unknown-fields: true
                # Optional: Transform rules
                severityMap:
                  type: object
                  description: "Map source severity values to standard severity levels (optional)"
                  additionalProperties:
                    type: string
                    enum: ["CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"]
                enabled:
                  type: boolean
                  description: "Whether this mapping is enabled (default: true)"
                  default: true
              # Additional properties for extensibility
              x-kubernetes-preserve-unknown-fields: true

