apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zenevents.zen.kube-zen.com
spec:
  group: zen.kube-zen.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
              - category
              - source
              - eventType
              - message
              - severity
              - timestamp
            properties:
              category:
                type: string
                description: "Event category (security, compliance, performance, observability, custom, etc - extensible)"
              source:
                type: string
                description: "Source tool that generated this event (trivy, falco, kyverno, audit, kube-bench, custom - extensible)"
              eventType:
                type: string
                description: "Type of event (vulnerability, runtime-threat, policy-violation, audit-event, benchmark, custom - extensible)"
              message:
                type: string
                description: "Event message/description"
              severity:
                type: string
                enum: ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
                description: "Severity level of the event"
              timestamp:
                type: string
                format: date-time
                description: "When the event was detected (RFC3339)"
              priority:
                type: integer
                minimum: 1
                maximum: 10
                default: 5
                description: "Priority level (1=highest, 10=lowest)"
              tags:
                type: array
                items:
                  type: string
                description: "Tags for categorization and filtering"
              metadata:
                type: object
                additionalProperties:
                  type: string
                description: "Additional metadata for observability tools (Grafana, Prometheus, Loki)"
              affectedResources:
                type: array
                items:
                  type: object
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                    apiVersion:
                      type: string
                description: "Kubernetes resources affected by this event"
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Active", "Resolved", "Acknowledged", "Archived"]
                default: "Active"
                description: "Current phase of the event"
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
                description: "Conditions of the event"
              firstSeen:
                type: string
                format: date-time
                description: "First time this event was seen"
              lastSeen:
                type: string
                format: date-time
                description: "Last time this event was seen"
              count:
                type: integer
                minimum: 0
                description: "Number of times this event occurred"
  scope: Namespaced
  names:
    plural: zenevents
    singular: zenevent
    kind: ZenEvent
    shortNames:
    - ze
    - zevt


