apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zenagentevents.zen.kube-zen.io
spec:
  group: zen.kube-zen.io
  names:
    kind: ZenAgentEvent
    listKind: ZenAgentEventList
    plural: zenagentevents
    singular: zenagentevent
    shortNames:
      - zaevent
      - zaevents
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["source", "category", "severity", "eventType"]
              properties:
                source:
                  type: string
                  description: "Tool that detected this event (trivy, falco, kyverno, etc)"
                category:
                  type: string
                  description: "Event category (security, compliance, performance)"
                severity:
                  type: string
                  description: "Severity level (critical, high, medium, low, info)"
                eventType:
                  type: string
                  description: "Type of event (vulnerability, runtime-threat, policy-violation)"
                resource:
                  type: object
                  description: "Affected Kubernetes resource"
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                details:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  description: "Event-specific details (flexible JSON)"
                detectedAt:
                  type: string
                  format: date-time
            status:
              type: object
              properties:
                synced:
                  type: boolean
                  description: "Whether this event has been synced to SaaS"
                lastSyncAttempt:
                  type: string
                  format: date-time
                syncError:
                  type: string
                saasEventId:
                  type: string
                  description: "Event ID in SaaS (after successful sync)"
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Source
          type: string
          jsonPath: .spec.source
        - name: Category
          type: string
          jsonPath: .spec.category
        - name: Severity
          type: string
          jsonPath: .spec.severity
        - name: Synced
          type: boolean
          jsonPath: .status.synced
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
